<a href="https://colab.research.google.com/github/AniTigerSib/AI-Methods/blob/main/AIlab2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

## Ознакомление с возможностями PyTorch

In [1]:
import torch
print(torch.__version__)

2.9.0+cpu


In [2]:
t = torch.empty(2,3,2)
t.dtype

torch.float32

In [6]:
t.type()
t.dim()
t.size()
t.shape

torch.Size([2, 3, 2])

In [7]:
torch.tensor([[1,2],[3,4],[5,6]],dtype=torch.float64)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]], dtype=torch.float64)

In [10]:
tf = t.int()
tf.dtype

torch.int32

## Лабораторная работа

In [1]:
import torch
import numpy as np

#### Task 1

In [6]:
a = torch.eye(4,3,dtype = torch.bool)
b = torch.zeros(4,3,dtype = torch.bool)

#### Task 2

In [8]:
t = a.logical_or(b)
t

tensor([[ True, False, False],
        [False,  True, False],
        [False, False,  True],
        [False, False, False]])

#### Task 3

In [10]:
t = t.float()
t.trace()

tensor(3.)

#### Task 4

In [12]:
t = t.ravel()
t

tensor([1., 0., 0., 0., 1., 0., 0., 0., 1., 0., 0., 0.])

#### Task 5

In [13]:
t.logical_not_()
t

tensor([0., 1., 1., 1., 0., 1., 1., 1., 0., 1., 1., 1.])

#### Task 6

In [14]:
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print(t.get_device())
t = t.cuda()
print(t.get_device())

-1
0
